var Wayfinder = require('./wayfinder')
var TileMap = require('./tilemap')

var { mapWidth, mapHeight } = require('./layout')

var tileMap = TileMap.fromString(`
................................
................................
................................
.......#####....................
.....###...#....................
.....#.....#....................
.....###...#....................
.......#####....................
................................
................................
................................
................................
`)
tileMap.print()

var start = { x: 9, y: 5 }
var finish = { x: 20, y: 5 }

var wayfinder = new Wayfinder()

wayfinder.getRouteBetween(start, finish, tileMap)
